name = "cdn-testing"
type = "javascript"
account_id = "76ebba46f2852b195a3e31d3e982d0fe"
workers_dev = true


[env.production]
route = "cdn-testing.duncte123.me/**"
zone_id = "cbaba59363cbabb9e1c08690cad548d0"
