name = "cdn-testing"
type = "webpack"
account_id = "76ebba46f2852b195a3e31d3e982d0fe"
workers_dev = true
webpack_config = "webpack.config.local.js"

[env.beta]
name = "cdn-testing-custom-domain"
route = "cdn-testing.duncte123.me/*"
zone_id = "cbaba59363cbabb9e1c08690cad548d0"
webpack_config = "webpack.config.beta.js"

[env.production]
name = "cdn-live"
route = "cdn.duncte123.me/*"
zone_id = "cbaba59363cbabb9e1c08690cad548d0"
webpack_config = "webpack.config.prod.js"
